
[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# NOTE: SPA redirect ensures client-side routing works after deployment.
# No further Netlify config needed for Vite React apps.
