// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pigewumujwiohakdfmur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZ2V3dW11andpb2hha2RmbXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Njc4MzksImV4cCI6MjA2NjM0MzgzOX0.zufUNUaBnPNtw9t4Iu9l5fn-Qzzexf1xNFBa3IlQUIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);